version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: agenda-dynamodb
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-inMemory']
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: agenda-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
